### ISSUE TITLE
Speed up semantic search. Find bottlenecks and resolve them.

### ISSUE THREAD

**Issue by joaquinvanschoren** [openml-labs/ai_search#34]

**Comment by PGijsbers** [comment]
This is a bit open-ended and underspecified. Are we talking about the whole pipeline (from submitting the query in a web browser to the results being displayed), or only specific parts? For what configuration (e.g., with query parsing step for filters, with a direct query, ...)?

**Comment by joaquinvanschoren** [comment]
The whole pipeline from submitting the query to getting the result, in the final configuration we will use when we release.
We simply don't have a clear view on how much time each step takes and how to speed it up. We need to clarify/measure this and then decide how to improve the workflow.

**Comment by SubhadityaMukherjee** [comment]
I do not think it is any longer possible to improve the performance without losing accuracy. Some major bottlenecks were identified though. For the sake of future records
1 - The LLM was being re-initialized at every call instead of being passed down through functions.

2 - Sending a sample query to the model before serving helps a lot. The first query usually loads the model fully to disk and the results are significantly faster from the second.

**Comment by SubhadityaMukherjee** [comment]
Given that, I think it makes sense to either close this, or push it to future plans.
